<?php

/**
 * @file
 * 02-MSG.inc
 *
 * Contiene los mensajes genéricos asociados a la respuesta SIS del sistema.
 * Se utiliza como respuesta al usuario.
 */

return [
  'MSG0000' => [
    'code' => 'MSG0000',
    'message' => 'El sistema está ocupado, inténtelo más tarde',
    'detail' => '',
  ],
  'MSG0001' => [
    'code' => 'MSG0001',
    'message' => 'Número de pedido repetido',
    'detail' => '',
  ],
  'MSG0002' => [
    'code' => 'MSG0002',
    'message' => 'El Bin de la tarjeta no está dado de alta en FINANET',
    'detail' => '',
  ],
  'MSG0003' => [
    'code' => 'MSG0003',
    'message' => 'El sistema está arrancando, inténtelo en unos momentos',
    'detail' => '',
  ],
  'MSG0004' => [
    'code' => 'MSG0004',
    'message' => 'Error de Autenticación',
    'detail' => '',
  ],
  'MSG0005' => [
    'code' => 'MSG0005',
    'message' => 'No existe método de pago válido para su tarjeta',
    'detail' => '',
  ],
  'MSG0006' => [
    'code' => 'MSG0006',
    'message' => 'Tarjeta ajena al servicio',
    'detail' => '',
  ],
  'MSG0007' => [
    'code' => 'MSG0007',
    'message' => 'Faltan datos, por favor compruebe que su navegador acepta cookies',
    'detail' => '',
  ],
  'MSG0008' => [
    'code' => 'MSG0008',
    'message' => 'Error en datos enviados. Contacte con su comercio.',
    'detail' => '',
  ],
];
